name: release-s3
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: get esp-idf
        run: |
          pip3 install --upgrade pip
          mkdir -p ~/esp
          cd ~/esp
          git clone -b v4.4 --recursive https://github.com/espressif/esp-idf.git
          cd ~/esp/esp-idf
          ./install.sh esp32s3
      - name: get LuatOS repo
        run: |
          cd ..
          git clone https://github.com/openLuat/LuatOS
      - name: build s3
        run: |
          source ~/esp/esp-idf/export.sh
          idf.py --version
          idf.py set-target esp32s3
          idf.py build
      - name: pack firmware
        run: |
          pip3 install -r tools/requirements.txt
          cd tools/
          sed -i 's/Release = false/Release = true/' config.toml
          python3 esp32v3.py -t esp32s3 -p
          cd ..
          mkdir firmware
          mv tools/* firmware
      - name: Upload firmware
        uses: actions/upload-artifact@main
        with:
          name: s3-release
          path: firmware/